### ISSUE TITLE
testing takes a long time

### ISSUE THREAD

**Issue by deepseek** [whai362/PSENet#113]
@whai362 
when running the testing command, it takes a long time to detect a single image.
is it not using the gpu?

**Comment by IuliiaSaveleva** [comment]
I'm facing the same problem, ~5-7 min per image. Torch GPU usage passes the tests: 
import torch
torch.cuda.current_device() => 0
torch.cuda.device(0) => <torch.cuda.device at 0x7efce0b03be0>
torch.cuda.device_count() => 1
torch.cuda.get_device_name(0) => @GeForce GTX 1070
torch.cuda.is_available() => True

I think, the reason might be in usage of pypse instead of c++ version of pse, that I could not compile yet. What version of pse do you use?

**Comment by deepseek** [comment]
hmmmm... the latest
each time I run the detection script it starts compiling and the takes a long time....

**Comment by manaralnaasan** [comment]
![image](https://user-images.githubusercontent.com/52988882/74626935-a85e8d80-5194-11ea-8d87-a7ea52bd1dfb.png)
OSError: [Errno 2] No such file or directory: '/home/avilab/Nassan/PSENet/data/ICDAR2015/Challenge4/ch4_training_images
i faced this problem could you help me please
thank you in advance
